### ISSUE TITLE
Processor for adding shadow

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity.org#6]
## Description

Some elements will need a shadow, and this should be configurable from Gutenberg. We are planning to add a class `has-shadow` to the elements where we want to apply it.

It could be applied inside any tag.

## Style
Each element with `has-shadow` should have these properties
```
box-shadow: 0 4px 14px 0 rgba(31,56,197,0.09), 0 2px 4px 0 rgba(31,56,197,0.12);
```

## Where to check
Inside `/common-styles/` page -> Div with shadow
Invision Homepage -> FAQ

**Comment by iamuchejude** [comment]
@SantosGuillamot This issue doesn't state if `shadow` is `box-shadow` or `text-shadow`. Apparently, this issue is to add `box-shadow`. I suggest it's updated from `has-shadow` to `has-box-shadow` incase of when might need to have `has-text-shadow` class.

The style in the description adds only `border` to the element which seems incomplete. Is there a reason for that?

**Comment by SantosGuillamot** [comment]
You're totally right. We are not using `text-shadow` right now, but it could be included in the future. This issue refers to `box-shadow` , so we can use `has-box-shadow` as you suggest.

I've also changed the style because it wasn't correct, thanks for the catch!

**Comment by iamuchejude** [comment]
I'm gonna update the class name of WordPress too. `has-shadow` will now be `has-box-shadow`.
